# Generated by Django 2.1.5 on 2019-03-20 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModelRelationships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('actor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='director', to='ModelRelationships.actor')),
            ],
        ),
        migrations.CreateModel(
            name='play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_name', models.CharField(max_length=255)),
                ('play_category', models.CharField(max_length=234)),
            ],
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_category', models.CharField(max_length=255)),
                ('role_name', models.CharField(max_length=243)),
            ],
        ),
        migrations.AddField(
            model_name='play',
            name='role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play', to='ModelRelationships.role'),
        ),
        migrations.AddField(
            model_name='director',
            name='play_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='director', to='ModelRelationships.play'),
        ),
        migrations.AddField(
            model_name='actor',
            name='role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor', to='ModelRelationships.play'),
        ),
    ]
